name: Open PR

on:
  push:

jobs:
  release:
    name: Open PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install --save-dev @octokit/core
      - run: node .github/workflows/openPR.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
